# Generated by Django 4.2.4 on 2023-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posts_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
