# Generated by Django 4.2.4 on 2024-01-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_categorys_posts_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categorys'),
            preserve_default=False,
        ),
    ]
