# Generated by Django 4.2.4 on 2024-01-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_posts_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='postCount',
        ),
        migrations.AddField(
            model_name='categorys',
            name='img',
            field=models.ImageField(default='', upload_to='static/img/cat'),
        ),
    ]
